server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbookshop?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: wyhui
#  security:
#    user:
#      name: user
#      password: 1234


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

bookshop:
  jwt:
    header: Authorization
    expire: 604800
    secret: enjknkmbnhgbghgbdddffrtthyjgnhgn
